# Data Analysis - Numpy Operations

<span class="mark">**NumPy - Find array dimensions - Use ndim**</span>

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
y = np.array([(1,2,3),(4,5,6)])

In [3]:
print("array dimension for x :", x.ndim)
print("array dimension for y :", y.ndim)

array dimension for x : 1
array dimension for y : 2


<span class="mark">**NumPy - Find memory used by each array element in bytes - Use itemsize**</span>

In [4]:
print("memory occupied by each element in array x :", x.itemsize)
print("memory occupied by each element in array y :", y.itemsize)

memory occupied by each element in array x : 4
memory occupied by each element in array y : 4


<span class="mark">**NumPy - Find datatype of array element - Use dtype**</span>

In [5]:
print("datatype of array element for x :", x.dtype)
print("datatype of array element for y :", y.dtype)

datatype of array element for x : int32
datatype of array element for y : int32


<span class="mark">**NumPy - Find count of array elements - Use size**</span>

In [6]:
print("count of array elements for x :", x.size)
print("count of array elements for y :", y.size)

count of array elements for x : 3
count of array elements for y : 6


<span class="mark">**NumPy - Find shape of array - Use shape**</span>

In [7]:
print("shape of array for x :", x.shape)
print("shape of array for y :", y.shape)

shape of array for x : (3,)
shape of array for y : (2, 3)


<span class="mark">**NumPy - Convert columns to rows in an array - Use reshape**</span>

In [8]:
print(x)
print(y)
print("shape of array for y before conversion :", y.shape)
print("Converting array now using reshape...")
y = y.reshape(3,2)
print(y)
print("shape of array for y after conversion :", y.shape)

[1 2 3]
[[1 2 3]
 [4 5 6]]
shape of array for y before conversion : (2, 3)
Converting array now using reshape...
[[1 2]
 [3 4]
 [5 6]]
shape of array for y after conversion : (3, 2)


<span class="mark">**NumPy - Generate equally spaced values between 2 numbers - Use linspace**</span>

In [9]:
print(" 5 values between 1 and 10... 1 and 10 included")
a = np.linspace(1,10,5)
print(a)

 5 values between 1 and 10... 1 and 10 included
[ 1.    3.25  5.5   7.75 10.  ]


In [10]:
print(" 10 values between 1 and 10... 1 and 10 included")
a = np.linspace(1,10,10)
print(a)

 10 values between 1 and 10... 1 and 10 included
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [11]:
print(" 15 values between 1 and 10... 1 and 10 included")
a = np.linspace(1,10,15)
print(a)

 15 values between 1 and 10... 1 and 10 included
[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]


In [12]:
print(" 20 values between 1 and 10... 1 and 10 included")
a = np.linspace(1,10,20)
print(a)

 20 values between 1 and 10... 1 and 10 included
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
