# Data Analysis - Numpy Arithmetic and String Operations

<span class="mark">**NumPy - Perform Arithmetic Operations**</span>

In [25]:
import numpy as np

In [26]:
# arange - Return uniformly spaced values within a given interval.
a = np.arange(9)

In [27]:
print('First array:')  
print(a)  
print('\n')

First array:
[0 1 2 3 4 5 6 7 8]




In [28]:
# reshape - Gives a new shape to an array without changing its data.
a = np.arange(9).reshape(3,3) 

In [29]:
print('First array:')  
print(a)  
print('\n')  

First array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]




In [30]:
print('Second array:')  
b = np.array([10,10,10]) 
print(b)  
print('\n') 

Second array:
[10 10 10]




In [31]:
print('Add the two arrays:') 
print(np.add(a,b)) 
print('\n')  

Add the two arrays:
[[10 11 12]
 [13 14 15]
 [16 17 18]]




In [32]:
print('Subtract the two arrays:')
print(np.subtract(a,b))
print('\n')  

Subtract the two arrays:
[[-10  -9  -8]
 [ -7  -6  -5]
 [ -4  -3  -2]]




In [33]:
print('Multiply the two arrays:')
print(np.multiply(a,b))
print('\n')

Multiply the two arrays:
[[ 0 10 20]
 [30 40 50]
 [60 70 80]]




In [34]:
print('Divide the two arrays:') 
print(np.divide(a,b))  
print('\n')

Divide the two arrays:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]




<span class="mark">**NumPy - Perform String Operations**</span>

**Character Addition**

In [35]:
import numpy as np 
print('Concatenate two strings:')
print(np.char.add(['hello'],[' xyz']))
print('\n')

Concatenate two strings:
['hello xyz']




In [36]:
print('Concatenation example:')
print(np.char.add(['hello', 'hi'],[' abc', ' xyz']))

Concatenation example:
['hello abc' 'hi xyz']


**Character Multiplication**

In [37]:
import numpy as np 
print(np.char.multiply('Hello ',3))

Hello Hello Hello 


**Center Characters**

In [38]:
import numpy as np 
# np.char.center(arr, width,fillchar) 
print(np.char.center('hello', 20,fillchar = '*'))

*******hello********


**Capitalize Characters**<br>This function returns the copy of the string with the first letter capitalized.

In [39]:
import numpy as np 
print(np.char.capitalize('hello world'))

Hello world


**Characters - Title Case Version**

In [40]:
import numpy as np 
print(np.char.title('hello how are you?'))

Hello How Are You?


**Characters - Lower Case**

In [41]:
import numpy as np 
print(np.char.lower(['HELLO','WORLD']))
print(np.char.lower('HELLO'))

['hello' 'world']
hello


**Characters - Upper Case**

In [42]:
import numpy as np 
print(np.char.upper('hello'))
print(np.char.upper(['hello','world']))

HELLO
['HELLO' 'WORLD']


**Split Characters - By default, whitespace is used as separator.Otherwise specified separator character is used**

In [43]:
import numpy as np 
print(np.char.split ('hello how are you?')) 
print(np.char.split ('JCCC,Overland Park,Kansas', sep = ','))

['hello', 'how', 'are', 'you?']
['JCCC', 'Overland Park', 'Kansas']


**Strip Characters - returns copy of array with elements stripped of specified characters**

In [44]:
import numpy as np 
print(np.char.strip('ashok arora','a'))
print(np.char.strip(['arora','admin','java'],'a'))

shok aror
['ror' 'dmin' 'jav']


**Replace Characters - returns new copy of input string, with all occurrences of sequence of char replaced by another given sequence.**

In [45]:
import numpy as np 
print(np.char.replace('He is a good boy', 'is', 'was'))

He was a good boy


**Boolean Array Indexing**

In [46]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

# Now we will print the items greater than 5 
print ('The items greater than 5 are:') 
print (x[x > 5])

The items greater than 5 are:
[ 6  7  8  9 10 11]


**NumPy Broadcasting : ability of NumPy to treat arrays of different shapes during arithmetic operations**

Rule 1: if 2 arrays differ in dimensions, the shape of the one with fewer dimensions is padded with ones on its leading left side
Rule 2: If the shape of the 2 arrays do not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape
Rule 3: if in any dimension the sizes disagree and neither is equal to 1, an error is raised. 

In [47]:
import numpy as np 

a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a + b 
print(c)

[11 22 33 44]


In [48]:
import numpy as np 
a = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]]) 
b = np.array([1,2,3])  
   
print('First array:')  
print(a)  
print('\n')   

print('Second array:')  
print(b)  
print('\n') 

print('First Array + Second Array') 
print(a + b)

First array:
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


Second array:
[1 2 3]


First Array + Second Array
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]
